apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "exec-ratelimit-tracingpolicy"
spec:
  tracepoints:
    - subsystem: "sched"
      event: "sched_process_exec"
      selectors:
        - matchActions:
          - action: Post